language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database politico_test;' -U postgres

script:
  - pytest --cov=ap

after_success:
  - coveralls